apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubernetesapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: kubernetesapp
  template:
    metadata:
      labels:
        app: kubernetesapp
    spec:
      containers:
      - name: app
        image: rynowak/kubernetesapp:latest
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: kubernetesapp
spec:
  selector:
    app: kubernetesapp
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80