apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-app
  labels:
    app: demo-app
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: demo-app
  template:
    metadata:
      labels:
        app: demo-app
    spec:
      containers:
      - name: demo-app
        image: rynowak/demo_app2:latest
        ports:
        - containerPort: 80
        readinessProbe:
            periodSeconds: 10
            successThreshold: 2
            initialDelaySeconds: 3
            httpGet:
              path: /healthz
              port: 80

---
apiVersion: v1
kind: Service
metadata:
  name: demo-app
spec:
  selector:
    app: demo-app
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80