version: "2.4"
services:
  forecast:
    image: rynowak/forecastapp-route-to-code:bad-thing-2
    ports:
      - "5001:80"
    build:
      context: ./forecastapp-route-to-code
    cpus: '1.0'
    mem_reservation: 512m

  result:
    image: rynowak/weatherapp-route-to-code:bad-thing-2
    ports:
      - "5000:80"
    depends_on:
      - forecast
    environment:
    - "FORECAST_SERVICE_URI=http://forecast:80/"
    build:
      context: ./weatherapp-route-to-code
    cpus: '1.0'
    mem_reservation: 512m